# Generated by Django 3.2 on 2021-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20210422_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapmodelroom',
            name='photo_room',
            field=models.TextField(blank=True, null=True),
        ),
    ]
